services:
  homarr:
    image: "ghcr.io/ajnart/homarr:latest"
    container_name: "homarr"
    restart: "unless-stopped"
    networks:
      - "proxy"
    environment:
      - LOCAL_DOMAIN_NAME=${LOCAL_DOMAIN_NAME}
      - BASE_VOLUME_DIRECTORY=${BASE_VOLUME_DIRECTORY}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "homarr-data:/app/data/configs"
      - "homarr-data:/data"
      - "homarr-data:/app/public/icons"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homarr.entrypoints=http"
      - "traefik.http.routers.homarr.rule=Host(`homarr.local.$LOCAL_DOMAIN_NAME`)"
      - "traefik.http.middlewares.homarr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.homarr.middlewares=homarr-https-redirect"
      - "traefik.http.routers.homarr-secure.entrypoints=https"
      - "traefik.http.routers.homarr-secure.rule=Host(`homarr.local.$LOCAL_DOMAIN_NAME`)"
      - "traefik.http.routers.homarr-secure.tls=true"
      - "traefik.http.routers.homarr-secure.service=homarr"
      - "traefik.http.services.homarr.loadbalancer.server.port=7575"
      - "traefik.docker.network=proxy"
networks:
  proxy:
    external: true

volumes:
  homarr-data:
    name: homarr-data



