services:
  plex:
    image: "plexinc/pms-docker:latest"
    container_name: "plex"
    restart: unless-stopped
    networks:
      - "proxy"
    security_opt:
      - no-new-privileges:true
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    environment:
      - TZ=America/New_York
      - PLEX_UID=1000
      - PLEX_GID=1000
      - VERSION=docker
      - LOCAL_DOMAIN_NAME=${LOCAL_DOMAIN_NAME}
      - BASE_VOLUME_DIRECTORY=${BASE_VOLUME_DIRECTORY}
      # Get Claim Token from here: https://www.plex.tv/claim/
    #      - PLEX_CLAIM="<get-from-above>"
    volumes:
      - "plex-config:/config"
      - "$BASE_VOLUME_DIRECTORY/plex/transcode:/transcode"
      - "$BASE_VOLUME_DIRECTORY/plex/media:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.entrypoints=http"
      - "traefik.http.routers.plex.rule=Host(`plex.local.$LOCAL_DOMAIN_NAME`)"
      - "traefik.http.middlewares.plex-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.plex.middlewares=plex-https-redirect"
      - "traefik.http.routers.plex-secure.entrypoints=https"
      - "traefik.http.routers.plex-secure.rule=Host(`plex.local.$LOCAL_DOMAIN_NAME`)"
      - "traefik.http.routers.plex-secure.tls=true"
      - "traefik.http.routers.plex-secure.service=plex"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
      - "traefik.docker.network=proxy"
networks:
  proxy:
    external: true


volumes:
  plex-config:
    name: plex-config
