services:
  kavita:
    container_name: kavita
    restart: "unless-stopped"
    image: jvmilazz0/kavita:latest
    environment:
      - TZ=America/New_York
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true
      - LOCAL_DOMAIN_NAME=${LOCAL_DOMAIN_NAME}
      - BASE_VOLUME_DIRECTORY=${BASE_VOLUME_DIRECTORY}
    volumes:
      - "$BASE_VOLUME_DIRECTORY/kavita/data/manga:/manga"
      - "$BASE_VOLUME_DIRECTORY/kavita/data/comics:/comics"
      - "$BASE_VOLUME_DIRECTORY/kavita/data/books:/books"
      - "kavita-config:/kavita/config"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kavita.entrypoints=http"
      - "traefik.http.routers.kavita.rule=Host(`kavita.local.$LOCAL_DOMAIN_NAME`)"
      - "traefik.http.middlewares.kavita-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.kavita.middlewares=kavita-https-redirect"
      - "traefik.http.routers.kavita-secure.entrypoints=https"
      - "traefik.http.routers.kavita-secure.rule=Host(`kavita.local.$LOCAL_DOMAIN_NAME`)"
      - "traefik.http.routers.kavita-secure.tls=true"
      - "traefik.http.routers.kavita-secure.service=kavita"
      - "traefik.http.services.kavita.loadbalancer.server.port=5000"
      - "traefik.docker.network=proxy"
networks:
  proxy:
    external: true

volumes:
  kavita-config:
    name: kavita-config