services:
  watchtower:
    image: "containrrr/watchtower"
    container_name: "watchtower"
    restart: "unless-stopped"
    networks:
      - "proxy"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
networks:
  proxy:
    external: true

