# Also see:
# https://github.com/mtkhawaja/posts/tree/main/containerizing-jenkins-dood-and-dind
services:
  jenkins:
    container_name: jenkins
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks:
      - proxy
    restart: unless-stopped
    environment:
      - LOCAL_DOMAIN_NAME=${LOCAL_DOMAIN_NAME}
      - BASE_VOLUME_DIRECTORY=${BASE_VOLUME_DIRECTORY}
      - JAVA_OPTS="-Djava.awt.headless=true"
    volumes:
      - "jenkins-data:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.entrypoints=http"
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.local.$LOCAL_DOMAIN_NAME`)"
      - "traefik.http.middlewares.jenkins-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.jenkins.middlewares=jenkins-https-redirect"
      - "traefik.http.routers.jenkins-secure.entrypoints=https"
      - "traefik.http.routers.jenkins-secure.rule=Host(`jenkins.local.$LOCAL_DOMAIN_NAME`)"
      - "traefik.http.routers.jenkins-secure.tls=true"
      - "traefik.http.routers.jenkins-secure.service=jenkins"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
networks:
  proxy:
    external: true

volumes:
  jenkins-data:
    name: jenkins-data
