#!/usr/bin/env zsh
#
# Documentation Reference:
# https://garagehq.deuxfleurs.fr/documentation/quick-start/
# https://garagehq.deuxfleurs.fr/documentation/reference-manual/configuration/
#
# Prints a single-node garage.toml to stdout with freshly generated secrets.
# Writes nothing, deploys nothing, and reads no other file in this repo.
#
# Progress goes to stderr, so stdout carries only the config:
#
#   ./services/garage/generate-garage-config.sh                # review it
#   ./services/garage/generate-garage-config.sh --yes | pbcopy # paste into Portainer
#
# Save the output to the path the compose file bind-mounts, which is
# $BASE_VOLUME_DIRECTORY/garage/data/garage.toml. An absolute host path is
# required because a stack deployed through Portainer resolves relative paths
# inside Portainer's own container.
#
# Run this once. Re-running mints new secrets: changing rpc_secret on a live
# cluster breaks node communication, and changing admin_token invalidates
# anything holding the old one. The keys and buckets you create with
# `garage key create` are stored in the metadata volume, not here, so they
# survive a config regeneration.
#
# Requires zsh, matching the other scripts in this repo. A copied file loses its
# execute bit, and `sh script.sh` then runs under dash on Debian and Ubuntu,
# which has no `pipefail`. The guard below re-runs the script under zsh.
#
# Usage:
#   ./services/garage/generate-garage-config.sh                          # prompts for the domain
#   ./services/garage/generate-garage-config.sh --domain lab.example.com # skip the prompt
#   ./services/garage/generate-garage-config.sh --yes                    # no prompts

# Kept POSIX-compatible: this runs before we know which shell we are in.
if [ -z "${ZSH_VERSION-}" ]; then
  if command -v zsh >/dev/null 2>&1 && [ -r "$0" ]; then
    exec zsh "$0" "$@"
  fi
  echo "ERROR: this script requires zsh. Install it, or run: zsh $0" >&2
  exit 1
fi

set -euo pipefail

DEFAULT_DOMAIN="local.example.com"

ASSUME_YES=0
DOMAIN_ARG=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    -y | --yes)
      ASSUME_YES=1
      shift
      ;;
    -d | --domain)
      [[ -n "${2:-}" ]] || {
        printf 'ERROR: --domain requires a value\n' >&2
        exit 1
      }
      DOMAIN_ARG="$2"
      shift 2
      ;;
    -h | --help)
      # Print the header comment block, stopping at the first non-comment line,
      # so this cannot drift out of sync with the file as it is edited.
      awk 'NR > 1 { if (/^#/) { sub(/^# ?/, ""); print } else { exit } }' "$0"
      exit 0
      ;;
    *)
      printf 'ERROR: unknown argument: %s (try --help)\n' "$1" >&2
      exit 1
      ;;
  esac
done

step() { printf '\n\033[1m==> %s\033[0m\n' "$1" >&2; }
info() { printf '    %s\n' "$1" >&2; }
die() {
  printf 'ERROR: %s\n' "$1" >&2
  exit 1
}

# ---------------------------------------------------------------------------
# 1. Resolve the domain
# ---------------------------------------------------------------------------
step "Resolving the domain"

if [[ -n "${DOMAIN_ARG}" ]]; then
  service_domain="${DOMAIN_ARG}"
  info "Using ${service_domain} (from --domain)"
elif [[ ${ASSUME_YES} -eq 1 || ! -t 0 ]]; then
  service_domain="${DEFAULT_DOMAIN}"
  info "Using ${service_domain} (default, not prompting)"
else
  # `read` returns non-zero on EOF, which Ctrl-D produces even on a tty. Without
  # this guard `set -e` would kill the script at the prompt with no message.
  reply=""
  if ! read -r "reply?    Domain services are published under [${DEFAULT_DOMAIN}]: "; then
    printf '\n' >&2
    info "No input read, falling back to the default"
  fi
  service_domain="${reply:-${DEFAULT_DOMAIN}}"
  info "Using ${service_domain}"
fi

info "This must match SERVICE_DOMAIN in the Traefik labels."

# ---------------------------------------------------------------------------
# 2. Generate the secrets
# ---------------------------------------------------------------------------
step "Generating secrets"

command -v openssl >/dev/null 2>&1 || die "'openssl' not found."

rpc_secret="$(openssl rand -hex 32)"
admin_token="$(openssl rand -base64 32)"
metrics_token="$(openssl rand -base64 32)"
info "rpc_secret, admin_token and metrics_token generated"

# ---------------------------------------------------------------------------
# 3. Emit the config
# ---------------------------------------------------------------------------
step "garage.toml (stdout)"

cat <<EOF
# Generated by services/garage/generate-garage-config.sh on $(date -u '+%Y-%m-%d')
# Contains secrets. Do not commit this file.
#
# Single-node configuration. See services/garage/docker-compose.yaml for how it
# is mounted and which ports Traefik routes.

# Paths inside the container. The compose file backs both with named volumes.
metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"

# lmdb is the engine upstream recommends for real deployments. The quick start
# uses sqlite, which is meant for trying it out.
db_engine = "lmdb"
metadata_auto_snapshot_interval = "6h"

# One node means one copy. There is no redundancy here: this relies on the
# underlying storage and on backups, not on Garage replication.
replication_factor = 1
compression_level = 2

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "${rpc_secret}"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
# Only used for virtual-host style requests (<bucket>.garage.${service_domain}).
# Path-style requests through Traefik ignore it.
root_domain = ".garage.${service_domain}"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".web.garage.${service_domain}"
index = "index.html"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "${admin_token}"
metrics_token = "${metrics_token}"
EOF

# ---------------------------------------------------------------------------
# 4. What to do with it
# ---------------------------------------------------------------------------
cat >&2 <<EOF

$(printf '\033[1m==> Next steps\033[0m')

    1. Save the output above to:
         \$BASE_VOLUME_DIRECTORY/garage/data/garage.toml

    2. Start it:
         docker compose \\
           --env-file "./docker-volumes/env-files/common.env" \\
           --file "./services/garage/docker-compose.yaml" up --detach

    3. Confirm the node applied its own layout:
         docker exec garage /garage status

    4. Create a key and a bucket:
         docker exec garage /garage key create my-key
         docker exec garage /garage bucket create my-bucket
         docker exec garage /garage bucket allow --read --write my-bucket --key my-key

       The key create output is the only time the secret key is shown.

    Point S3 clients at https://garage.${service_domain} with region "garage",
    and set path-style addressing.
EOF
