services:
  broker:
    image: docker.io/library/redis:8
    restart: unless-stopped
    volumes:
      - paperless-broker-data:/data
    networks:
      - paperless

  db:
    image: docker.io/library/postgres:18
    restart: unless-stopped
    volumes:
      - paperless-db-data:/var/lib/postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-paperless}
      POSTGRES_USER: ${POSTGRES_USER:-paperless}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-paperless}
    networks:
      - paperless

  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.25
    restart: unless-stopped
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
    networks:
      - paperless

  tika:
    image: docker.io/apache/tika:latest
    restart: unless-stopped
    networks:
      - paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    environment:
      # See https://docs.paperless-ngx.com/configuration/
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_DBNAME: ${POSTGRES_DB:-paperless}
      PAPERLESS_DBUSER: ${POSTGRES_USER:-paperless}
      PAPERLESS_DBPASS: ${POSTGRES_PASSWORD:-paperless}
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_URL: https://paperless.local.$LOCAL_DOMAIN_NAME
      PAPERLESS_ALLOWED_HOSTS: paperless.local.$LOCAL_DOMAIN_NAME
      PAPERLESS_USE_X_FORWARD_HOST: "true"
      PAPERLESS_USE_X_FORWARD_PORT: "true"
      LOCAL_DOMAIN_NAME: ${LOCAL_DOMAIN_NAME}
      BASE_VOLUME_DIRECTORY: ${BASE_VOLUME_DIRECTORY}
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ${BASE_VOLUME_DIRECTORY}/paperless/data/export:/usr/src/paperless/export
      - ${BASE_VOLUME_DIRECTORY}/paperless/data/consume:/usr/src/paperless/consume
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paperless.entrypoints=http"
      - "traefik.http.routers.paperless.rule=Host(`paperless.local.$LOCAL_DOMAIN_NAME`)"
      - "traefik.http.middlewares.paperless-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.paperless.middlewares=paperless-https-redirect"
      - "traefik.http.routers.paperless-secure.entrypoints=https"
      - "traefik.http.routers.paperless-secure.rule=Host(`paperless.local.$LOCAL_DOMAIN_NAME`)"
      - "traefik.http.routers.paperless-secure.tls=true"
      - "traefik.http.routers.paperless-secure.service=paperless"
      - "traefik.http.services.paperless.loadbalancer.server.port=8000"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      - paperless

volumes:
  data:
  media:
  paperless-db-data:
  paperless-broker-data:

networks:
  paperless:
  proxy:
    external: true